---
default_stages:
  - commit
  - push
repos:
  -
    repo: 'https://github.com/pre-commit/pre-commit-hooks.git'
    rev: v3.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-json
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
  - repo: 'https://github.com/jumanjihouse/pre-commit-hooks.git'
    rev: 2.1.4
    hooks:
      - id: shellcheck
      - id: shfmt
  - repo: 'https://github.com/adrienverge/yamllint'
    rev: v1.25.0
    hooks:
      - id: yamllint
        exclude: '^tests\/.*\.yaml'
  - repo: 'https://github.com/jorisroovers/gitlint.git'
    rev: v0.15.0
    hooks:
      - id: gitlint
        stages:
          - commit-msg
  - repo: local
    hooks:
      - id: validate-yaml
        name: 'Run rubocop'
        entry: 'rake rubocop'
        language: system
        pass_filenames: false
